version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: jobs-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-jobs}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jobs123}
      POSTGRES_DB: ${POSTGRES_DB:-jobsdb}
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  ml:
    build: ./ml
    container_name: jobs-ml
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "${ML_PORT:-8000}:8000"

  api:
    build: ./api
    container_name: jobs-api
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-jobs}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jobs123}
      POSTGRES_DB: ${POSTGRES_DB:-jobsdb}
      API_PORT: ${API_PORT:-4000}
      ML_PORT: ${ML_PORT:-8000}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5173}
    depends_on:
      - db
      - ml
    ports:
      - "${API_PORT:-4000}:4000"

  frontend:
    build: ./frontend
    container_name: jobs-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:4000}
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  db_data:
